### ISSUE TITLE
Noob question - how do I use this?

### ISSUE THREAD

**Issue by GrPK** [orn8/tinfoil#72]
Hello, kind of a noob question, new to this kind of stuff.. If it isn't a bother for you, could you let me know what should I do after I add your source the TinFoil? Nothing changes after I restart the app.

Thanks

**Comment by orn8** [comment]
make sure you don't have a typo and filled everything in correctly, otherwise it seems like you did everything correctly. you're supposed to add the source to tinfoil and it should just work. i recently added an alternate source option in the repo, delete the one you added and try adding this:

```
Protocol: https
Host: raw.githubusercontent.com
Path: orn8/tinfoil/main/tinfoil.json
Title: oragne shop
```

if it still doesn't work, try reading the README for any issues you are experiencing, otherwise the shops included in oragne shop are down.

**Comment by GrPK** [comment]
Yeah, I had already have the sources added before I added your source, IDK why I expected something magical to happen. Sorry for the issue, I will close it.
